defaultFilter: &defaultFilter
  enable: true
  rules:
    # all packets are allowed by default
    - allow:*
    # except for the following rules
    - block:WindSeedClientNotify
    - block:PlayerLuaShellNotify

loggingDir: log
baseDomain: example.com
autoSignUp: true
passSignIn: false
httpServer:
  enable: true
  addr: 0.0.0.0:2888
  tls:
    enable: false
    addr: 0.0.0.0:8443
gateServer:
  - name: http
    title: http
    dispatchUrl: http://127.0.0.1:20001/query_cur_region
  - name: https
    title: https
    dispatchUrl: https://127.0.0.1:20001/query_cur_region
  - name: os_beta01
    title: 127.0.0.1:22102
    addr: 127.0.0.1:22102
gameServer:
  enable: true
  addr: 0.0.0.0:20071
  filter: *defaultFilter
database:
  driver: sqlite
  dsn: file:data/hk4e-emu.db?cache=shared&mode=rwc
